import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '../components/Header';
const inter = Inter({ subsets: ['latin'] });
import Firstanime from '@/components/Firstanime';
import Technology from '@/components/Technology';
import Khadamat from '@/components/Khadamat';
import Nomoone from '@/components/Nomoone';
import Footer from '@/components/Footer';
export default function Home() {
  return (
    <>
      <Head>
        <title>Arkweb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Ark.ico" />
        <link href="https://cdn.dribbble.com/assets/dribbble-ball-mark-2bd45f09c2fb58dbbfb44766d5d1d07c5a12972d602ef8b32204d28fa3dda554.svg"></link>

        <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css" rel="stylesheet" type="text/css" />
      </Head>
      <Header />
      <main>
        <Firstanime />
       </main>
    </>
  );
}
